source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.1.16'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'safer_rails_console', path: '../../../'
