language: ruby
sudo: false

services:
  - postgresql

bundler_args: --without test --jobs 3 --retry 3
before_install:
  - gem install bundler

before_script:
  - cp spec/internal/database.yml.travis spec/internal/rails_5_0/config/database.yml
  - cp spec/internal/database.yml.travis spec/internal/rails_5_1/config/database.yml
  - cp spec/internal/database.yml.travis spec/internal/rails_5_2/config/database.yml
  - cp spec/internal/database.yml.travis spec/internal/rails_6_0/config/database.yml

script:
  - bundle exec rubocop
  - bundle exec rspec

rvm:
  - 2.5.6

gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

matrix:
  fast_finish: true
