default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: safer_rails_console_development

test:
  <<: *default
  database: safer_rails_console_test

production:
  <<: *default
  database: safer_rails_console_production
