# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4fef097c478f61e83f935e1fc5ff580d0358faf63fe43808d08c2c72a4b46d55e78392a837cbc0e095adc832dd357250467392ad0f57d44d51ee0c2aacce17

test:
  secret_key_base: e520cd2570e3064811274bc423d447dd5dba1b5ff5bd1b10093c2cd874fdd2c9d26f00050cf98285ccba9ee24a46c0b73811e0fd1e7ca98a4d827faa205ba770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
