default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: <%= ENV['DB_PORT'] || 5432 %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: safer_rails_console_development

test:
  <<: *default
  database: safer_rails_console_test

production:
  <<: *default
  database: safer_rails_console_production
